// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class 5Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void 5() {
    driver.get("https://vikisews.com/vykrojki/muzhskie-vykrojki/hudi-dzhejkob/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    js.executeScript("window.scrollTo(0,51.20000076293945)");
    js.executeScript("window.scrollTo(0,1300)");
    driver.findElement(By.cssSelector(".product-param:nth-child(6)")).click();
    driver.findElement(By.id("addToCart")).click();
    driver.findElement(By.linkText("Перейти в корзину")).click();
    driver.findElement(By.cssSelector(".cart-icon__rm")).click();
  }
}
